# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.2.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.TTY/kafka: "false"
    io.kubernetes.cri-o.TTY/zookeeper: "false"
    io.podman.annotations.autoremove/kafka: "FALSE"
    io.podman.annotations.autoremove/zookeeper: "FALSE"
    io.podman.annotations.init/kafka: "FALSE"
    io.podman.annotations.init/zookeeper: "FALSE"
    io.podman.annotations.privileged/kafka: "FALSE"
    io.podman.annotations.privileged/zookeeper: "FALSE"
    io.podman.annotations.publish-all/kafka: "FALSE"
    io.podman.annotations.publish-all/zookeeper: "FALSE"
  creationTimestamp: "2022-10-25T16:03:27Z"
  labels:
    app: zookeeper-pod
  name: zookeeper-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - bin/zookeeper-server-start.sh config/zookeeper.properties
    env:
    - name: LOG_DIR
      value: /tmp/logs
    image: quay.io/strimzi/kafka:0.31.1-kafka-3.2.3
    name: zookeeper
    ports:
    - containerPort: 2181
      hostPort: 2181
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  - command:
    - sh
    - -c
    - bin/kafka-server-start.sh config/server.properties --override listeners=${KAFKA_LISTENERS}
      --override advertised.listeners=${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=${KAFKA_ZOOKEEPER_CONNECT}
    env:
    - name: KAFKA_ADVERTISED_LISTENERS
      value: PLAINTEXT://localhost:9092
    - name: LOG_DIR
      value: /tmp/logs
    - name: KAFKA_LISTENERS
      value: PLAINTEXT://0.0.0.0:9092
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    image: quay.io/strimzi/kafka:0.31.1-kafka-3.2.3
    name: kafka
    ports:
    - containerPort: 9092
      hostPort: 9092
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
